application: netegreek
version: 1
runtime: php
api_version: 1
threadsafe: yes

handlers:

- url: /(.*\.(gif|png|jpg|ico|js|css|txt|json|wof|ttf|svg))
  static_files: \1
  upload: (.*\.(gif|png|jpg|ico|js|css|txt|json|wof|ttf|svg))
  
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /contact
  script: contact_me.php
  
- url: .*
  script: main.php


